version: '3.5'

services:
  db:
    image: postgres:latest
    environment:
      PGUSER: nnpia
      POSTGRES_USER: nnpia
      POSTGRES_PASSWORD: nnpia
      PGDATA: /data/postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5433:5432"



volumes:
  postgres-db:
    driver: local